version: '3.8'

services:
  documind-api:
    build: .
    container_name: documind-api
    ports:
      - "8000:8000"
    environment:
      - MODEL_NAME=mistralai/Mistral-7B-Instruct-v0.2
      - EMBEDDING_MODEL=sentence-transformers/all-MiniLM-L6-v2
      - DEVICE=cpu
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - LOG_LEVEL=INFO
    volumes:
      - ./data:/app/data
      - ./models:/app/models
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  documind-ui:
    build: .
    container_name: documind-ui
    ports:
      - "8501:8501"
    environment:
      - API_BASE_URL=http://documind-api:8000/api
    depends_on:
      - documind-api
    command: streamlit run app/ui.py --server.port=8501 --server.address=0.0.0.0
    restart: unless-stopped

volumes:
  data:
  models:
